name: Build Release
on:
  workflow_dispatch:

jobs:
  build:
   runs-on: macos-latest

   steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: chmod +x ./Resources/compile.release.sh
            ./Resources/compile.release.sh
        shell: bash
        
      - name: Upload .ipa
        uses: actions/upload-artifact@v2.2.4
        with:
         name: chromatic.ipa
         path: "build/Release/chromatic.ipa"
      - name: Upload .deb
        uses: actions/upload-artifact@v2.2.4
        with:  
         name: chromatic.rel.ci.deb
         path: "build/Release/chromatic.rel.ci.deb"
