name: Build Release
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-11
    env:
      THEOS: theos
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: brew install ldid xz
      - name: Setup Theos
        uses: actions/checkout@master
        with:
          repository: theos/theos
          ref: 8771215f765e774bfefdacc6ddf0e151c2973d49
          path: theos
          submodules: recursive
      - name: Download SDKs
        run: |
          curl -LO https://github.com/SamHep0803/iOS-13-Patched-SDK/archive/master.zip 
          TMP=$(mktemp -d)
          unzip master.zip -d $TMP
          mv $TMP/iOS-13-Patched-SDK-master/*.sdk theos/sdks
          rm -r master.zip $TMP # TODO: it should be 
          brew install dpkg
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build
        run: |
          chmod +x ./Resources/compile.release.action.sh
          /bin/bash -c ./Resources/compile.release.action.sh
      - name: Upload .ipa
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "chromatic.relsan.${{ env.build_timestamp }}.ipa"
          path: "build/artifact/chromatic.relsan.${{ env.build_timestamp }}.ipa"
      - name: Upload .deb
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "chromatic.rel.ci.${{ env.build_timestamp }}.deb"
          path: "build/artifact/chromatic.rel.ci.${{ env.build_timestamp }}.deb"
