name: Build Release4
on:
  workflow_dispatch:

name: Install Theos and Build Release4
description: 'Install Theos and prepare it for building projects'
author: 'Randomblock1'
inputs:
  theos-dir:
    description: 'Where to install Theos (relative to the repo workspace itself)'
    required: false
    default: theos
  theos-src:
    description: 'Where to clone Theos itself from (git URL)'
    required: false
    default: 'https://github.com/theos/theos'
  theos-sdks:
    description: 'Where to clone the iOS SDKs from (git URL)'
    required: false
    default: 'https://github.com/theos/sdks'
runs:
  using: "composite"
  steps:
    - name: prepare environment
      shell: bash
      run: |
        brew install ldid make
        echo "THEOS=$GITHUB_WORKSPACE/${{ inputs.theos-dir }}" >> $GITHUB_ENV
        PATH="/usr/local/opt/make/libexec/gnubin:$PATH" >> $GITHUB_ENV
        echo "Succesfully installed tools!"

    - name: get theos
      shell: bash
      run: |
        if [ ! -d "${{ github.workspace }}/${{ inputs.theos-dir }}" ]; then
          git clone ${{ inputs.theos-src }} ${{ github.workspace }}/${{ inputs.theos-dir }} --recursive
          echo "Theos successfully obtained!"
        else
          echo "Theos already cached, skipping..."
        fi

    - name: get sdks
      shell: bash
      run: |
        if [ ! -d "${{ github.workspace }}/${{ inputs.theos-dir }}/sdks" ]; then
          cd ${{ github.workspace }}/${{ inputs.theos-dir }}/sdks
          curl -sLO ${{ inputs.theos-sdks }}/archive/master.zip
          TMP=$(mktemp -d)
          7z x master.zip -o$TMP
          mv $TMP/*-master/*.sdk $THEOS/sdks
          rm -r master.zip $TMP
        else
          echo "Theos SDKs already cached, skipping..."
        fi

jobs:
  build:
   runs-on: macos-11
   steps:
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build
        run: |
            chmod +x ./Resources/compile.release2.sh
            /bin/bash -c ./Resources/compile.release2.sh
      - name: Upload .ipa
        uses: actions/upload-artifact@v2.2.4
        with:
         name: chromatic.ipa
         path: "build/Release/chromatic.ipa"
      - name: Upload .deb
        uses: actions/upload-artifact@v2.2.4
        with:
         name: chromatic.rel.ci.deb
         path: "build/Release/chromatic.rel.ci.deb"
