name: Build Release3
on:
  workflow_dispatch:

jobs:
  build:
   runs-on: macos-latest
   steps:
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build
        run: |
            chmod +x ./Resources/compile.release2.sh
            /bin/bash -c ./Resources/compile.release2.sh 
      - name: Upload .ipa
        uses: actions/upload-artifact@v2.2.4
        with:
         name: chromatic.ipa
         path: "build/Release/chromatic.ipa"
      - name: Upload .deb
        uses: actions/upload-artifact@v2.2.4
        with:  
         name: chromatic.rel.ci.deb
         path: "build/Release/chromatic.rel.ci.deb"
